version: "3.4"
volumes:
  db-data:
    external: false

services:
  postgres:
    container_name: "dework-postgres"
    image: postgres:latest
    environment:
      POSTGRES_USER: --
      POSTGRES_PASSWORD: --
    volumes:
      - db-data:/usr/local/pgsql/data
  rails:
    environment:
      BLOCKCYPHER_API: --
      NETWORK: test
      CURRENCY: bcy
      POSTGRES_USER: --
      POSTGRES_PASSWORD: --
    container_name: "dework_backend"
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000
    depends_on:
      - postgres
