version: "3.4"

services:
  rails:
    image: registry.digitalocean.com/dework/rails:latest
    environment:
      BLOCKCYPHER_API: 996808f22e4d4e959d661f43a1ed0af4
      POSTGRES_URL: --
      NETWORK: main
      CURRENCY: btc
      GITHUB: --
      SECRET_KEY_BASE: --
      VIRTUAL_HOST: logic.tallypeer.com
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: logic.tallypeer.com
    ports:
      - 5000
    container_name: "dework_backend"
networks:
  default:
    external:
      name: proxy