version: "3.4"
services:
  rails:
    image: registry.digitalocean.com/dework/rails_staging:latest
    environment:
      BLOCKCYPHER_API: --
      NETWORK: test
      CURRENCY: bcy
      GITHUB: --
      SECRET_KEY_BASE: --
      POSTGRES_URL: --
      VIRTUAL_HOST: logic-staging.tallypeer.com
      VIRTUAL_PORT: 3001
      LETSENCRYPT_HOST: logic-staging.tallypeer.com
    ports:
      - 3001
    container_name: "dework_backend_staging"
    depends_on:
      - postgres

networks:
  default:
    external:
      name: proxy