version: "3.4"
volumes:
  db-data:
    external: false

services:
  postgres:
    container_name: "dework_postgres"
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/usr/local/pgsql/data
  rails:
    image: registry.digitalocean.com/dework/rails:latest
    environment:
      BLOCKCYPHER_API: 996808f22e4d4e959d661f43a1ed0af4
      NETWORK: main
      CURRENCY: btc
      GITHUB: --
      SECRET_KEY_BASE: --
      POSTGRES_USER: --
      POSTGRES_PASSWORD: --
      VIRTUAL_HOST: logic.tallypeer.com
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: logic.tallypeer.com
    ports:
      - 5000
    container_name: "dework_backend"
    depends_on:
      - postgres

networks:
  default:
    external:
      name: proxy